apiVersion: v1
kind: Service
metadata:
  name: music-external
  namespace: music
  labels:
    name: music-external
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: web
    tier: frontend
